# This is a basic workflow to help you get started with Actions

name: Det_test

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Det_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: generate timings.txt and re-push
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          python scripts/det_timings.py results/timings.txt
          git push
